on: [push, workflow_dispatch]

jobs:
  build:
    name: Run build script on MacOS
    runs-on: macos-10.15
    env:
        PARALLEL_JOBS: 10
        MACOSX_DEPLOYMENT_TARGET: 10.14
        CROSS_OVER_VERSION: 20.0.4
        ARTIFACT_NAME: wine.${CROSS_OVER_VERSION}.win32on64

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare
        run: ./prepare_env.sh

      - name: Get Source
        run: ./get_source.sh

      - name: Apply Patches
        run: ./apply_patches.sh

      - name: Tar patched Wine Sources
        run: tar -czvf wine-sources-patched.tar.gz ./sources/wine

      - name: Upload patched Wine Sources
        uses: actions/upload-artifact@v2
        with:
          name: wine-sources
          path: wine-sources-patched.tar.gz

      - name: Build LLVM
        run: ./build_llvm.sh

      - name: Build Clang
        run: ./build_clang.sh

      - name: Tar Build Tools
        run: tar -czvf build-tools.tar.gz ./install/build-tools

      - name: Upload Build Tools
        uses: actions/upload-artifact@v2
        with:
          name: build-tools
          path: build-tools.tar.gz

      - name: Build Wine
        run: ./build_wine.sh

      - name: Tar Wine
        run: tar -czvf ${ARTIFACT_NAME}.tar.gz ./install/wine

      - name: Upload Wine
        uses: actions/upload-artifact@v2
        with:
          name: ${ARTIFACT_NAME}
          path: ${ARTIFACT_NAME}.tar.gz
