name: Wine-Crossover-MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
    # avoid weird linker errors with Xcode 10 and later
    MACOSX_DEPLOYMENT_TARGET: 10.14
    # crossover source code to be downloaded
    CROSS_OVER_SOURCE_URL: https://media.codeweavers.com/pub/crossover/source/crossover-sources-20.0.4.tar.gz
    CROSS_OVER_LOCAL_FILE: crossover-20.0.4
    # directories / files inside the downloaded tar file directory structure
    LLVM_MAKEDIR: $GITHUB_WORKSPACE/sources/clang/llvm
    CLANG_MAKEDIR: $GITHUB_WORKSPACE/sources/clang/clang
    WINE_CONFIGURE: $GITHUB_WORKSPACE/sources/wine/configure
    DXVK_BUILDSCRIPT: $GITHUB_WORKSPACE/sources/dxvk/package-release.sh
    # build directories
    BUILDROOT: $GITHUB_WORKSPACE/build
    LLVM_BUILDDIR: $GITHUB_WORKSPACE/build/llvm
    CLANG_BUILDDIR: $GITHUB_WORKSPACE/build/clang
    # target directories for installation (must be relative to $GITHUB_WORKSPACE)
    TOOLS_INSTALLROOT: install/build-tools
    WINE_INSTALLROOT: install/wine
    DXVK_INSTALLROOT: install/dxvk
    # artifact names
    BUILDTOOLS: build-tools
    WINE_SOURCES: crossover-20.0.4-patched
    DXVK_SOURCES: dxvk-sources-patched
    WINE_INSTALLATION: wine
    DXVK_INSTALLATION: dxvk

jobs:
  wine-crossover:
    runs-on:  macos-10.15

    steps:


      ############ Prepare Workspace / Environment ##############

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # build tools
          brew install  cmake            \
                        ninja            \
                        mingw-w64        \

          # build dependencies for wine / crossover
          brew install  freetype         \
                        bison            \
                        krb5             \
                        faudio           \
                        sdl2             \
                        gphoto2          \
                        gst-plugins-base \
                        mpg123           \
                        little-cms2      \
                        libpng           \
                        molten-vk

          # dependencies for dxvk
          brew install  coreutils \
                        meson     \
                        glslang

      - name: Add bison & krb5 to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix krb5)/bin" >> $GITHUB_PATH

      - name: Add llvm/clang to $PATH (for later)
        run: |
          set -eu
          echo "$GITHUB_WORKSPACE/${{ env.TOOLS_INSTALLROOT }}/bin" >> $GITHUB_PATH


      ############ Download and Prepare Source Code ##############

      - name: Get Source
        run:  |
          curl -o ${{ env.CROSS_OVER_LOCAL_FILE }}.tar.gz ${{ env.CROSS_OVER_SOURCE_URL }}

      - name: Upload Original Crossover Sources
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CROSS_OVER_LOCAL_FILE }}
          path: ${{ env.CROSS_OVER_LOCAL_FILE }}.tar.gz

      - name: Extract Source
        run:  |
          tar xf ${{ env.CROSS_OVER_LOCAL_FILE }}.tar.gz

      - name: Apply Patches
        run: ./apply_patches.sh

      - name: Tar Patched Crossover Sources
        run: tar -czvf ${{ env.WINE_SOURCES }}.tar.gz ./sources/wine

      - name: Upload Patched Crossover Sources
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.WINE_SOURCES }}
          path: ${{ env.WINE_SOURCES }}.tar.gz

      - name: Tar Patched DXVK Sources
        run: tar -czvf ${{ env.DXVK_SOURCES }}.tar.gz ./sources/dxvk

      - name: Upload Patched DXVK Sources
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DXVK_SOURCES }}
          path: ${{ env.DXVK_SOURCES }}.tar.gz


      ############ Build LLVM / Clang ##############

      - name: Configure LLVM
        run: |
          mkdir -p ${{ env.LLVM_BUILDDIR }}
          pushd ${{ env.LLVM_BUILDDIR }}
          cmake -G Ninja \
                -DLLVM_TARGETS_TO_BUILD=X86 \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/${{ env.TOOLS_INSTALLROOT }}" \
                ${{ env.LLVM_MAKEDIR }}
          popd

      - name: Build LLVM
        run: |
          pushd ${{ env.LLVM_BUILDDIR }}
          Ninja
          popd

      - name: Install LLVM
        run: |
          pushd ${{ env.LLVM_BUILDDIR }}
          Ninja install
          popd

      - name: Configure Clang
        run: |
          mkdir -p ${{ env.CLANG_BUILDDIR }}
          pushd ${{ env.CLANG_BUILDDIR }}
          cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/${{ env.TOOLS_INSTALLROOT }}" \
                ${{ env.CLANG_MAKEDIR }}
          popd

      - name: Build Clang
        run: |
          pushd ${{ env.CLANG_BUILDDIR }}
          Ninja
          popd

      - name: Install Clang
        run: |
          pushd ${{ env.CLANG_BUILDDIR }}
          Ninja install
          popd

      - name: Tar Build Tools
        run: tar -czf ${{ env.BUILDTOOLS }}.tar.gz ${{ env.TOOLS_INSTALLROOT }}

      - name: Upload Build Tools
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILDTOOLS }}
          path: ${{ env.BUILDTOOLS }}.tar.gz


      ############ Build DXVK ##############

      - name: Build DXVK
        run: |
          PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH" ${{ env.DXVK_BUILDSCRIPT }} master $GITHUB_WORKSPACE/${{ env.DXVK_INSTALLROOT }} --no-package

      - name: Tar DXVK
        run: tar -czf ${{ env.DXVK_INSTALLATION }}.tar.gz ${{ env.DXVK_INSTALLROOT }}

      - name: Upload DXVK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DXVK_INSTALLATION }}
          path: ${{ env.DXVK_INSTALLATION }}.tar.gz


      ############ Build 64bit Version ##############

      - name: Configure wine64
        env:
          CC: clang
          CXX: clang++
          # Xcode12 by default enables '-Werror,-Wimplicit-function-declaration' (49917738)
          # this causes wine(64) builds to fail so needs to be disabled.
          # https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes
          CFLAGS: "-Wno-implicit-function-declaration -Wno-deprecated-declarations -Wno-format"
        run: |
          export SDL2_CFLAGS="-I$(brew --prefix sdl2)/include"
          export SDL2_LIBS="-L$(brew --prefix sdl2)/lib"

          export PNG_CFLAGS="-I$(brew --prefix libpng)/include"
          export PNG_LIBS="-L$(brew --prefix libpng)/lib"

          export LDFLAGS="-L $(brew --prefix molten-vk)/lib"

          mkdir -p ${{ env.BUILDROOT }}/wine64
          pushd ${{ env.BUILDROOT }}/wine64
          ${{ env.WINE_CONFIGURE }} \
                    --enable-win64 \
                    --disable-tests \
                    --without-alsa \
                    --without-capi \
                    --without-dbus \
                    --without-inotify \
                    --without-oss \
                    --without-pulse \
                    --without-udev \
                    --without-v4l2 \
                    --without-gsm \
                    --with-png \
                    --with-sdl \
                    --with-vulkan \
                    --without-x
          popd

      - name: Build wine64
        run: |
          pushd ${{ env.BUILDROOT }}/wine64
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
          popd

      - name: Install wine64
        run: |
          pushd ${{ env.BUILDROOT }}/wine64
          make install-lib DESTDIR="$GITHUB_WORKSPACE/${{ env.WINE_INSTALLROOT }}"
          popd


      ############ Build 32bit Version (WoW64) ##############

      - name: Configure wine32on64
        env:
          CC: clang
          CXX: clang++
          # Xcode12 by default enables '-Werror,-Wimplicit-function-declaration' (49917738)
          # this causes wine(64) builds to fail so needs to be disabled.
          # https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes
          CFLAGS: "-Wno-implicit-function-declaration -Wno-deprecated-declarations -Wno-format"
        run: |
          export SDL2_CFLAGS="-I$(brew --prefix sdl2)/include"
          export SDL2_LIBS="-L$(brew --prefix sdl2)/lib"

          export PNG_CFLAGS="-I$(brew --prefix libpng)/include"
          export PNG_LIBS="-L$(brew --prefix libpng)/lib"

          mkdir -p ${{ env.BUILDROOT }}/wine32on64
          pushd ${{ env.BUILDROOT }}/wine32on64
          ${{ env.WINE_CONFIGURE }} \
                    --enable-win32on64 \
                    --with-wine64=${{ env.BUILDROOT }}/wine64 \
                    --disable-tests \
                    --without-alsa \
                    --without-capi \
                    --without-dbus \
                    --without-inotify \
                    --without-oss \
                    --without-pulse \
                    --without-udev \
                    --without-v4l2 \
                    --disable-winedbg \
                    --without-cms \
                    --without-gstreamer \
                    --without-gsm \
                    --with-png \
                    --with-sdl \
                    --without-vulkan \
                    --without-x
          popd

      - name: Build wine32on64
        run: |
          pushd ${{ env.BUILDROOT }}/wine32on64
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
          popd

      - name: Install wine32on64
        run: |
          pushd ${{ env.BUILDROOT }}/wine32on64
          make install-lib DESTDIR="$GITHUB_WORKSPACE/${{ env.WINE_INSTALLROOT }}"
          popd


      ############ Bundle and Upload Deliverable ##############

      - name: Tar Wine
        run: tar -czvf ${{ env.WINE_INSTALLATION }}.tar.gz ${{ env.WINE_INSTALLROOT }}

      - name: Upload Wine
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.WINE_INSTALLATION }}
          path: ${{ env.WINE_INSTALLATION }}.tar.gz
