on: [push, workflow_dispatch]

jobs:
  build:
    name: Run build script on MacOS
    runs-on: macos-10.15
    env:
        PARALLEL_JOBS: 8
        MACOSX_DEPLOYMENT_TARGET: 10.15
        CROSS_OVER_VERSION: 20.0.4

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare
        run: ./prepare_env.sh

      - name: Get Source
        run: ./get_source.sh

      - name: Apply Patches
        run: ./apply_patches.sh

      - name: Build LLVM
        run: ./build_llvm.sh

      - name: Build Clang
        run: ./build_clang.sh

      - name: Build Wine
        run: ./build_wine.sh

      - name: Install Wine
        run: ./install_wine.sh

      - name: 'Tar files'
        run: tar -czvf wine.win32on64.tar.gz ./install/win32on64

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: wine.win32on64
          path: wine.win32on64.tar.gz
