on: [push, workflow_dispatch]
env:
    PARALLEL_JOBS: 10
    MACOSX_DEPLOYMENT_TARGET: 10.14
    CROSS_OVER_VERSION: 20.0.4
    WINE_SOURCES: wine-sources-patched
    BUILDTOOLS: build-tools
    INSTALLROOT_TOOLS: ${{ github.workspace }}/install/build-tools
    SKIP_BUILD: ${{ true }}

jobs:
  prepare:
    name: Prepare Environment and Tools
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare
        run: ./prepare_env.sh

      - name: Get Source
        run: ./get_source.sh

      - name: Apply Patches
        run: ./apply_patches.sh

      - name: Tar patched Wine Sources
        run: tar -czvf ${{ env.WINE_SOURCES }}.tar.gz ./sources/wine

      - name: Upload patched Wine Sources
        uses: actions/upload-artifact@v2
        with:
          name: wine-sources
          path: ${{ env.WINE_SOURCES }}.tar.gz

      - name: Build LLVM
        if: ${{ ! env.SKIP_BUILD }}
        run: ./build_llvm.sh

      - name: Build Clang
        if: ${{ ! env.SKIP_BUILD }}
        run: ./build_clang.sh

      - name: Tar Build Tools
        if: ${{ ! env.SKIP_BUILD }}
        run: tar -czf ${{ env.BUILDTOOLS }}.tar.gz ${{ env.INSTALLROOT_TOOLS }}

      - name: Upload Build Tools
        if: ${{ ! env.SKIP_BUILD }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILDTOOLS }}
          path: ${{ env.BUILDTOOLS }}.tar.gz

  build_wine:
    name: Build Wine
    runs-on: macos-10.15
    needs: prepare
    strategy:
      matrix:
        wine_arch: [win64, win32on64]
    env:
      WINE_ARCH: ${{ matrix.wine_arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Wine Sources
        uses: actions/download-artifact@v2
        with:
          name: wine-sources

      - name: Extract Wine Sources
        run: ls -al . ; ls -al * ; tar -xvf ${{ env.WINE_SOURCES }}.tar.gz

      - name: Download Build Tools
        if: ${{ ! env.SKIP_BUILD }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.BUILDTOOLS }}

      - name: Extract Build Tools
        if: ${{ ! env.SKIP_BUILD }}
        run: tar -xf ${{ env.BUILDTOOLS }}.tar.gz

      - name: Build Wine
        if: ${{ ! env.SKIP_BUILD }}
        env:
          INSTALLROOT_WINE: "${{ github.workspace }}/install/wine_${{ env.CROSSOVER_VERSION }}_${{ matrix.wine_arch }}"
        run: ./build_wine.sh

      - name: Tar Wine
        if: ${{ ! env.SKIP_BUILD }}
        env:
          WINE_TARFILE: wine_${{ env.CROSS_OVER_VERSION }}_${{ matrix.wine_arch }}
          INSTALLROOT_WINE: "${{ github.workspace }}/install/wine_${{ env.CROSSOVER_VERSION }}_${{ matrix.wine_arch }}"
        run: tar -czvf ${{ env.WINE_TARFILE }}.tar.gz ${{ env.INSTALLROOT_WINE }}

      - name: Upload Wine
        if: ${{ ! env.SKIP_BUILD }}
        uses: actions/upload-artifact@v2
        env:
          WINE_TARFILE: wine_${{ env.CROSS_OVER_VERSION }}_${{ matrix.wine_arch }}
        with:
          name: ${{ env.WINE_TARFILE }}
          path: ${{ env.WINE_TARFILE }}.tar.gz
