on: [push, workflow_dispatch]
env:
    PARALLEL_JOBS: 10
    MACOSX_DEPLOYMENT_TARGET: 10.14
    CROSS_OVER_VERSION: 20.0.4
    INSTALLROOT_TOOLS: ${{ github.workspace }}/install/build-tools

jobs:
  prepare:
    name: Prepare Environment and Tools
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare
        run: ./prepare_env.sh

      - name: Get Source
        run: ./get_source.sh

      - name: Apply Patches
        run: ./apply_patches.sh

      - name: Tar patched Wine Sources
        run: tar -czvf wine-sources-patched.tar.gz ./sources/wine

      - name: Upload patched Wine Sources
        uses: actions/upload-artifact@v2
        with:
          name: wine-sources
          path: wine-sources-patched.tar.gz

      - name: Build LLVM
        run: ./build_llvm.sh

      - name: Build Clang
        run: ./build_clang.sh

      - name: Tar Build Tools
        run: tar -czf build-tools.tar.gz ${{ env.INSTALLROOT_TOOLS }}

      - name: Upload Build Tools
        uses: actions/upload-artifact@v2
        with:
          name: build-tools
          path: build-tools.tar.gz

  build_wine:
    name: Build Wine
    runs-on: macos-10.15
    needs: prepare
    strategy:
      matrix:
        wine_arch: [win64, win32on64]
    env:
      WINE_ARCH: ${{ matrix.wine_arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Extract Wine Sources
        run: mkdir -p ./sources/wine && tar -xzf wine-sources-patched.tar.gz ./sources/wine

      - name: Extract Build Tools
        run: mkdir -p ${{ env.INSTALLROOT_TOOLS }} && tar -xzf build-tools.tar.gz ${{ env.INSTALLROOT_TOOLS }}

      - name: Build Wine
        env:
          INSTALLROOT_WINE: "${{ github.workspace }}/install/wine_${{ env.CROSSOVER_VERSION }}_${{ matrix.wine_arch }}"
        run: ./build_wine.sh

      - name: Tar Wine
        env:
          WINE_TARFILE: wine_${{ env.CROSS_OVER_VERSION }}_${{ matrix.wine_arch }}
          INSTALLROOT_WINE: "${{ github.workspace }}/install/wine_${{ env.CROSSOVER_VERSION }}_${{ matrix.wine_arch }}"
        run: tar -czvf ${{ env.WINE_TARFILE }}.tar.gz ${{ env.INSTALLROOT_WINE }}

      - name: Upload Wine
        uses: actions/upload-artifact@v2
        env:
          WINE_TARFILE: wine_${{ env.CROSS_OVER_VERSION }}_${{ matrix.wine_arch }}
        with:
          name: ${{ env.WINE_TARFILE }}
          path: ${{ env.WINE_TARFILE }}.tar.gz
