on: [push]

jobs:
  build:
    name: Run build script on MacOS
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare
        run: ./prepare_env.sh

      - name: Get Source
        run: ./get_source.sh

      - name: Build LLVM
        run: ./build_llvm.sh

      - name: Build Clang
        run: ./build_clang.sh

      - name: Build Wine
        run: ./build_wine.sh

      - uses: actions/upload-artifact@v2
        with:
          name: crossover
          path: ./
